=== Sunxiaoshao/XML-WEB-/Library.dtd
<<<<<<< HEAD
<!DOCTYPE Library [

<!ELEMENT Library (Book+,Member+)>
<!ELEMENT Book (Title,Author,Price,Publisher,Gost)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Gost (#PCDATA)>
<!ELEMENT Member (Name,Address)>
<!ELEMENT Name (FirstName,MiddleName,LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Address (HouseNumber,Street,City)>
<!ELEMENT HouseNumber (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>

<!ATTLIST Book BookId CDATA "000000"> 

=======
<!DOCTYPE Library [

<!ELEMENT Library (Book+,Member+)>
<!ELEMENT Book (Title,Author,Price,Publisher,Gost)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Gost (#PCDATA)>
<!ELEMENT Member (Name,Address)>
<!ELEMENT Name (FirstName,MiddleName,LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Address (HouseNumber,Street,City)>
<!ELEMENT HouseNumber (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>

<!ATTLIST Book BookId CDATA "000000"> 

>>>>>>> 9ae124e732f83e07e53e031a1b9e8ec6526084b8
]>

=== Sunxiaoshao/XML-WEB-/Library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "Library.dtd">

<Library>
	<Book BookId = "01">
		<Title>Classics</Title>
		<Name>The Tragedy of Hamlet</Name>
		<Author>George Raymond Richard Martin</Author>
                <Price>$45</Price>
		<Publisher>People's publishing house</Publisher>
		<Cost>$38</Cost>	
	</Book>
	<Member>
		<Name>
			<FirstName>Black</FirstName>
			<MiddleName>Sweeney</MiddleName>
			<LastName>Sutton</LastName>
		</Name>
		<Address>
			<HouseNumber>706</HouseNumber>
			<Street>The Yangtze river street</Street>
			<City>Jing Zhou</City>
		</Address>
	</Member>
</Library>
